wisper-tech-demo-2/config/routes.rb
Rails.application.routes.draw do
  root to: "authors#index"
  resources :books
  resources :authors
end

wisper-tech-demo-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wisper-tech-demo-2/app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

wisper-tech-demo-2/app/models/book.rb
# NOTES
# - imagine puts is putting a job on some ActiveJob queue instead of just printing text

# class Book < ApplicationRecord
#   belongs_to :author
#
#   validates :title, presence: true
#
#   before_validation :ensure_title_has_a_value
#   after_create :notify_fans, :notify_author, :update_create_stats
#   after_destroy :update_destroy_stats
#
#   private
#
#     def ensure_title_has_a_value
#       self.title = "Untitled" if title.blank?
#     end
#
#     def notify_fans
#       (1..10).each do |i|
#         puts "Yo fan #{i}! You've gotta read this!"
#       end
#     end
#
#     def notify_author
#       puts "Hey, #{self.author.first_name}, your book was successfully created. Noice!"
#     end
#
#     def update_create_stats
#       update_stats(:create)
#     end
#
#     def update_destroy_stats
#       update_stats(:destroy)
#     end
#
#     def update_stats(type)
#       case type
#         when :create
#           puts "increment the existing books counter somewhere."
#           puts "increment the created books counter somewhere."
#         when :destroy
#           puts "decrement the existing books counter somewhere."
#           puts "increment the destroyed books counter somewhere."
#         else
#           puts "wtf"
#       end
#     end
# end

# class Book < ApplicationRecord
#   belongs_to :author
#
#   validates :title, presence: true
#
#   before_validation :ensure_title_has_a_value
#   after_create :notify_fans, :notify_author, :update_create_stats
#   after_destroy :update_destroy_stats
#
#   private
#
#     # internal -> good
#     def ensure_title_has_a_value
#       self.title = "Untitled" if title.blank?
#     end
#
#     # side effect -> bad
#     def notify_fans
#       (1..10).each do |i|
#         puts "Yo fan #{i}! You've gotta read this!"
#       end
#     end
#
#     # side effect -> bad
#     def notify_author
#       puts "Hey, #{self.author.first_name}, your book was successfully created. Noice!"
#     end
#
#     # side effect -> bad
#     def update_create_stats
#       update_stats(:create)
#     end
#
#     # side effect -> bad
#     def update_destroy_stats
#       update_stats(:destroy)
#     end
#
#     # side effect -> bad
#     def update_stats(type)
#       case type
#         when :create
#           puts "increment the existing books counter somewhere."
#           puts "increment the created books counter somewhere."
#         when :destroy
#           puts "decrement the existing books counter somewhere."
#           puts "increment the destroyed books counter somewhere."
#         else
#           puts "wtf"
#       end
#     end
# end

class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: true

  before_validation :ensure_title_has_a_value

  private

    def ensure_title_has_a_value
      self.title = "Untitled" if title.blank?
    end
end

wisper-tech-demo-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wisper-tech-demo-2/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

wisper-tech-demo-2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:author_id, :title, :description)
    end
end

wisper-tech-demo-2/app/helpers/application_helper.rb
module ApplicationHelper
end

wisper-tech-demo-2/app/helpers/authors_helper.rb
module AuthorsHelper
end

wisper-tech-demo-2/app/helpers/books_helper.rb
module BooksHelper
end

wisper-tech-demo-2/app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

wisper-tech-demo-2/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

wisper-tech-demo-2/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

wisper-tech-demo-2/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

wisper-tech-demo-2/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

wisper-tech-demo-2/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id,
                               Author.all,
                               :id,
                               Proc.new { |author| "#{author.last_name + ', '}#{author.first_name}" } %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

wisper-tech-demo-2/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

wisper-tech-demo-2/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.author_id %></td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

wisper-tech-demo-2/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

wisper-tech-demo-2/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @book.author_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

wisper-tech-demo-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WisperTechDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "Authors", authors_path %>
      <%= link_to "Books", books_path %>
    </header>
    <hr />
    <%= yield %>
  </body>
</html>